plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.hmtl
  - README.hmtl
  - LICENSE.hmtl
  - COPYING.hmtl
  - CODE_OF_CONDUCT.hmtl
  - CONTRIBUTING.hmtl
  - ISSUE_TEMPLATE.hmtl
  - PULL_REQUEST_TEMPLATE.hmtl
  - tasks/MSBuild.hmtl
