title: Pipelines2Actions
description: Use this guidance to rewrite Azure Pipelines (Build and Release Tasks) on GitHub Actions.
markdown: kramdown

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
